// app/layout.js
import localFont from "next/font/local";
import "./globals.css";

// Mengimpor font lokal
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata aplikasi
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Komponen RootLayout polos
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
